language: python
python:
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g eclint

script:
  - flake8 .
  - eclint check *.py sites/*.py
